import { defineTool } from "@better-fetch/tools";

const TOOL: string = "crates_io_package_scraper";
type Input = Record<string, any>;
type Output = Record<string, any>;

function record(value: unknown): Record<string, any> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, any> : {}; }
function array(value: unknown): any[] { return Array.isArray(value) ? value : []; }
function text(value: unknown): string { return typeof value === "string" ? value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#0?39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\s+/g," ").trim() : value == null ? "" : String(value); }
function num(value: unknown): number { const n=Number(typeof value === "string" ? value.replace(/[^0-9.+-]/g,"") : value); return Number.isFinite(n)?n:0; }
function attr(tag:string,name:string):string { const e=name.replace(/[.*+?^{}()|[\]\\]/g,"\\$&"); return text(tag.match(new RegExp(e+"=[\\\"']([^\\\"']*)[\\\"']","i"))?.[1]); }
function absolute(value:string,base:string):string { try { const u=new URL(value,base); u.hash=""; return u.toString(); } catch { return value; } }
function json(body:string):any { try { return JSON.parse(body); } catch { throw new Error("source returned invalid JSON"); } }
function tag(block:string,name:string):string { const e=name.replace(/[.*+?^{}()|[\]\\]/g,"\\$&"); return text(block.match(new RegExp("<"+e+"(?:\\s[^>]*)?>([\\s\\S]*?)<\\/"+e+">","i"))?.[1]); }
function compact<T extends Record<string,any>>(value:T):T { return Object.fromEntries(Object.entries(value).filter(([,v])=>v!==undefined&&v!==null&&v!=="")) as T; }
async function get(bf:any,url:string,strategy:"http"|"auto"="http") { const r=await bf.fetch({url,strategy,return_response_text:true,include_html:true,extra_headers:{accept:"application/json,text/html,application/xml,text/xml;q=0.9,*/*;q=0.5","user-agent":"Mozilla/5.0 (compatible; BetterFetchTool/0.1; +https://betterfetch.co/tools)"}}); if(r.status&&r.status>=400) throw new Error("source returned HTTP "+r.status); return {body:r.body_text??r.html??"",url:r.final_url??url}; }
function repoName(value:string):string { const clean=value.trim().replace(/^https?:\/\/github\.com\//i,"").replace(/\.git$/i,"").replace(/^\/+|\/+$/g,""); if(!/^[\w.-]+\/[\w.-]+$/.test(clean)) throw new Error("repository must be owner/name or a GitHub repository URL"); return clean; }
function meta(html:string,key:string):string { for(const m of html.matchAll(/<meta\b[^>]*>/gi)){ const t=m[0]; if([attr(t,"property"),attr(t,"name"),attr(t,"itemprop")].some(v=>v.toLowerCase()===key.toLowerCase())) return attr(t,"content"); } return ""; }
function title(html:string):string { return meta(html,"og:title")||text(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]); }
function hash(value:string):string { let h=2166136261; for(let i=0;i<value.length;i++){ h^=value.charCodeAt(i); h=Math.imul(h,16777619); } return "fnv1a32-"+(h>>>0).toString(16).padStart(8,"0"); }

export default defineTool<Input,Output>(async (input,bf) => {
  const limit=Math.max(1,Math.min(num(input.limit)||20,1000));
  if(TOOL==="sitemap_extractor") { const u=new URL(String(input.url)); const source=/\.xml(?:$|\?)/i.test(u.pathname)?u.toString():new URL("/sitemap.xml",u).toString(); const r=await get(bf,source); const rows=[...r.body.matchAll(/<url\b[\s\S]*?<\/url>/gi)].slice(0,limit).map(m=>compact({url:tag(m[0],"loc"),last_modified:tag(m[0],"lastmod"),change_frequency:tag(m[0],"changefreq"),priority:num(tag(m[0],"priority"))||undefined})).filter(x=>x.url); const indexes=[...r.body.matchAll(/<sitemap\b[\s\S]*?<\/sitemap>/gi)].slice(0,limit).map(m=>compact({url:tag(m[0],"loc"),last_modified:tag(m[0],"lastmod")})).filter(x=>x.url); const urls=rows.length?rows:indexes; return {source_url:r.url,count:urls.length,urls}; }
  if(TOOL==="robots_txt_analyzer") { const requested=new URL(String(input.url)); const source=requested.pathname.endsWith("robots.txt")?requested.toString():new URL("/robots.txt",requested).toString(); const r=await get(bf,source); let agents="*"; const directives:any[]=[]; for(const raw of r.body.split(/\r?\n/)){ const line=raw.replace(/\s+#.*$/,"").trim(); const m=line.match(/^([\w-]+)\s*:\s*(.*)$/); if(!m) continue; const directive=m[1].toLowerCase(); const value=m[2].trim(); if(directive==="user-agent") agents=value||"*"; directives.push({user_agent:agents,directive,value}); } return {source_url:r.url,count:directives.length,directives}; }
  if(TOOL==="rss_feed_scraper") { const r=await get(bf,String(input.url)); const blocks:string[]=r.body.match(/<item\b[\s\S]*?<\/item>/gi)??r.body.match(/<entry\b[\s\S]*?<\/entry>/gi)??[]; const items=blocks.slice(0,limit).map((b:string)=>compact({title:tag(b,"title"),link:tag(b,"link")||attr(b.match(/<link\b[^>]*>/i)?.[0]??"","href"),published_at:tag(b,"pubDate")||tag(b,"published")||tag(b,"updated"),author:tag(b,"author")||tag(b,"dc:creator"),guid:tag(b,"guid")||tag(b,"id"),summary:tag(b,"description")||tag(b,"summary")})).filter((x:any)=>x.title&&x.link); return {source_url:r.url,count:items.length,items}; }
  if(TOOL==="open_graph_extractor") { const r=await get(bf,String(input.url),"auto"); const properties:any[]=[]; const seen=new Set<string>(); for(const m of r.body.matchAll(/<meta\b[^>]*>/gi)){ const t=m[0]; const property=attr(t,"property")||attr(t,"name")||attr(t,"itemprop"); const content=attr(t,"content"); if(!property||!content||seen.has(property)) continue; if(/^(og:|twitter:|description$|author$)/i.test(property)){seen.add(property);properties.push({property,content});} } const canonicalTag=r.body.match(/<link\b[^>]*rel=["'][^"']*canonical[^"']*["'][^>]*>/i)?.[0]??""; if(attr(canonicalTag,"href")) properties.push({property:"canonical",content:absolute(attr(canonicalTag,"href"),r.url)}); return {source_url:r.url,count:properties.length,properties}; }
  if(TOOL==="json_ld_extractor") { const r=await get(bf,String(input.url),"auto"); const documents:any[]=[]; for(const m of r.body.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){ try { const parsed=JSON.parse(m[1].trim().replace(/^<!--|-->$/g,"")); const values=Array.isArray(parsed)?parsed:[parsed]; for(const value of values){ const o=record(value); const type=Array.isArray(o["@type"])?o["@type"].join(", "):text(o["@type"]||"Unknown"); documents.push({type,json:JSON.stringify(value)}); if(documents.length>=limit) break; } } catch {} if(documents.length>=limit) break; } return {source_url:r.url,count:documents.length,documents}; }
  if(TOOL==="webpage_links_extractor") { const r=await get(bf,String(input.url),"auto"); const base=new URL(r.url); const scope=String(input.scope||"all"); const links:any[]=[]; const seen=new Set<string>(); for(const m of r.body.matchAll(/<a\b[^>]*>[\s\S]*?<\/a>/gi)){ const href=attr(m[0],"href"); if(!href||/^(mailto:|tel:|javascript:|#)/i.test(href)) continue; const url=absolute(href,r.url); if(seen.has(url)) continue; const domain=new URL(url).hostname; const linkScope=domain===base.hostname?"internal":"external"; if(scope!=="all"&&scope!==linkScope) continue; seen.add(url); links.push(compact({url,text:text(m[0]),scope:linkScope,rel:attr(m[0],"rel"),domain})); if(links.length>=limit) break; } return {source_url:r.url,count:links.length,links}; }
  if(TOOL==="website_technology_detector") { const r=await get(bf,String(input.url),"auto"); const checks:[string,string,RegExp][]=[["Next.js","framework",/\/_next\/|__NEXT_DATA__/i],["React","javascript",/react(?:\.production)?|data-reactroot/i],["Vue.js","framework",/vue(?:\.runtime)?|data-v-/i],["Nuxt","framework",/__NUXT__|\/_nuxt\//i],["SvelteKit","framework",/_app\/immutable|data-svelte/i],["WordPress","cms",/wp-content|wp-includes/i],["Shopify","ecommerce",/cdn\.shopify\.com|Shopify\.theme/i],["Google Analytics","analytics",/googletagmanager\.com|gtag\(/i],["Cloudflare","cdn",/cdn-cgi|cloudflare/i],["Vercel","hosting",/vercel|\.vercel\.app/i],["Tailwind CSS","css",/--tw-|tailwind/i]]; const technologies=checks.filter(([, ,re])=>re.test(r.body)).map(([name,category,re])=>({name,category,evidence:r.body.match(re)?.[0]??name})); return {source_url:r.url,count:technologies.length,technologies}; }
  if(TOOL==="webpage_change_fingerprint") { const r=await get(bf,String(input.url),"auto"); const max=Math.max(1000,Math.min(num(input.max_chars)||100000,500000)); const normalized=text(r.body.replace(/<(script|style|noscript|svg)[\s\S]*?<\/\1>/gi," ")).slice(0,max); const snapshots=[{url:r.url,title:title(r.body),fingerprint:hash(normalized),normalized_chars:normalized.length,word_count:normalized?normalized.split(/\s+/).length:0}]; return {source_url:r.url,count:1,snapshots}; }
  if(TOOL==="github_releases_scraper") { const repo=repoName(String(input.repository)); const source=`https://github.com/${repo}/releases`; const r=await get(bf,source,"auto"); const releases:any[]=[]; const seen=new Set<string>(); const escaped=repo.replace(/[.*+?^{}()|[\]\\]/g,"\\$&"); const re=new RegExp("<a\\b[^>]*href=[\\\"'](/"+escaped+"/releases/tag/([^\\\"']+))[\\\"'][^>]*>([\\s\\S]*?)<\\/a>","gi"); let match:RegExpExecArray|null; while((match=re.exec(r.body))&&releases.length<Math.min(limit,50)){const tagName=decodeURIComponent(match[2]);if(seen.has(tagName))continue;seen.add(tagName);releases.push({tag:tagName,name:text(match[3])||tagName,url:absolute(match[1],"https://github.com"),prerelease:/pre-release/i.test(match[3]),draft:false});} return {source_url:r.url,count:releases.length,releases}; }
  if(TOOL==="github_issues_scraper") { const repo=repoName(String(input.repository)); const state=String(input.state||"open"); const query=state==="all"?"is:issue":`is:issue state:${state}`; const source=`https://github.com/${repo}/issues?q=${encodeURIComponent(query)}`; const r=await get(bf,source,"auto"); const issues:any[]=[]; const seen=new Set<number>(); const escaped=repo.replace(/[.*+?^{}()|[\]\\]/g,"\\$&"); const re=new RegExp("<a\\b[^>]*href=[\\\"'](/"+escaped+"/issues/(\\d+))[\\\"'][^>]*>([\\s\\S]*?)<\\/a>","gi"); let match:RegExpExecArray|null; while((match=re.exec(r.body))&&issues.length<Math.min(limit,50)){const number=Number(match[2]);const issueTitle=text(match[3]);if(!issueTitle||seen.has(number))continue;seen.add(number);issues.push({number,title:issueTitle,url:absolute(match[1],"https://github.com"),state});} return {source_url:r.url,count:issues.length,issues}; }
  if(TOOL==="github_trending_scraper") { const lang=text(input.language).toLowerCase(); const since=String(input.since||"daily"); const source=`https://github.com/trending/${encodeURIComponent(lang)}?since=${since}`; const r=await get(bf,source,"auto"); const repositories=(r.body.match(/<article\b[\s\S]*?<\/article>/gi)??[]).slice(0,Math.min(limit,25)).map((b:string,i:number)=>{const a=b.match(/<h2[\s\S]*?<a\b[^>]*>[\s\S]*?<\/a>/i)?.[0]??""; const path=attr(a,"href"); const counters=[...b.matchAll(/<a\b[^>]*href=["'][^"']*\/(?:stargazers|forks)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(m=>num(text(m[1]))); return compact({rank:i+1,repository:text(a),url:path?absolute(path,"https://github.com"):"",description:text(b.match(/<p\b[^>]*>([\s\S]*?)<\/p>/i)?.[1]),language:text(b.match(/itemprop=["']programmingLanguage["'][^>]*>([\s\S]*?)<\//i)?.[1]),stars:counters[0],forks:counters[1],stars_in_period:num(text(b.match(/([\d,.]+)\s+stars?\s+(?:today|this week|this month)/i)?.[1]))});}); return {source_url:r.url,count:repositories.length,repositories}; }
  if(TOOL==="stack_exchange_search") { const p=new URLSearchParams({site:String(input.site||"stackoverflow"),q:String(input.query),pagesize:String(Math.min(limit,50)),order:"desc",sort:"relevance"}); if(input.tagged)p.set("tagged",String(input.tagged)); const source=`https://api.stackexchange.com/2.3/search/advanced?${p}`; const r=await get(bf,source); const questions=array(record(json(r.body)).items).map(x=>record(x)).map(x=>compact({question_id:num(x.question_id),title:text(x.title),url:text(x.link),score:num(x.score),answers:num(x.answer_count),is_answered:Boolean(x.is_answered),tags:array(x.tags).map(text).join(", "),owner:text(record(x.owner).display_name),created_at:new Date(num(x.creation_date)*1000).toISOString(),last_activity_at:new Date(num(x.last_activity_date)*1000).toISOString()})); return {source_url:r.url,count:questions.length,questions}; }
  if(TOOL==="devto_articles_scraper") { const p=new URLSearchParams({per_page:String(Math.min(limit,30))}); if(input.tag)p.set("tag",String(input.tag)); if(input.username)p.set("username",String(input.username)); const source=`https://dev.to/api/articles?${p}`; const r=await get(bf,source); const articles=array(json(r.body)).map(x=>record(x)).map(x=>compact({id:num(x.id),title:text(x.title),url:text(x.url),author:text(record(x.user).name||record(x.user).username),tags:text(x.tag_list),published_at:text(x.published_at),reactions:num(x.public_reactions_count),comments:num(x.comments_count),reading_minutes:num(x.reading_time_minutes),description:text(x.description)})); return {source_url:r.url,count:articles.length,articles}; }
  if(TOOL==="crates_io_package_scraper") { const crate=String(input.crate).trim(); const source=`https://crates.io/api/v1/crates/${encodeURIComponent(crate)}`; const r=await get(bf,source); const body=record(json(r.body)); const c=record(body.crate); const version=record(body.version); const packages=[compact({name:text(c.name),version:text(c.max_version||version.num),description:text(c.description),downloads:num(c.downloads),recent_downloads:num(c.recent_downloads),license:text(version.license),repository:text(c.repository),documentation:text(c.documentation),homepage:text(c.homepage),updated_at:text(c.updated_at),keywords:array(body.keywords).map(x=>text(record(x).keyword)).join(", ")})]; return {source_url:r.url,count:packages.length,packages}; }
  if(TOOL==="rubygems_package_scraper") { const gem=String(input.gem).trim(); const source=`https://rubygems.org/api/v1/gems/${encodeURIComponent(gem)}.json`; const r=await get(bf,source); const x=record(json(r.body)); const deps=record(x.dependencies); const packages=[compact({name:text(x.name),version:text(x.version),description:text(x.info),downloads:num(x.downloads),version_downloads:num(x.version_downloads),licenses:array(x.licenses).map(text).join(", "),homepage:text(x.homepage_uri),source_code:text(x.source_code_uri),documentation:text(x.documentation_uri),created_at:text(x.version_created_at),dependencies:[...array(deps.runtime),...array(deps.development)].map(v=>{const d=record(v);return text(d.name)+" "+text(d.requirements)}).join(", ")})]; return {source_url:r.url,count:1,packages}; }
  if(TOOL==="cisa_kev_scraper") { const source="https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json"; const r=await get(bf,source); const q=text(input.query).toLowerCase(); const vulnerabilities=array(record(json(r.body)).vulnerabilities).map(x=>record(x)).filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).slice(0,Math.min(limit,100)).map(x=>compact({cve:text(x.cveID),vendor:text(x.vendorProject),product:text(x.product),name:text(x.vulnerabilityName),date_added:text(x.dateAdded),due_date:text(x.dueDate),action:text(x.requiredAction),ransomware_use:text(x.knownRansomwareCampaignUse),notes:text(x.notes)})); return {source_url:r.url,count:vulnerabilities.length,vulnerabilities}; }
  if(TOOL==="dblp_publication_search") { const source=`https://dblp.org/search/publ/api?q=${encodeURIComponent(String(input.query))}&format=json&h=${Math.min(limit,50)}`; const r=await get(bf,source); const hits=array(record(record(record(json(r.body)).result).hits).hit); const publications=hits.map(h=>record(record(h).info)).map(x=>{const authorsValue=record(x.authors).author; const authors=array(authorsValue).length?array(authorsValue):[authorsValue]; return compact({title:text(x.title),authors:authors.map(v=>text(record(v).text||v)).filter(Boolean).join(", "),venue:text(x.venue),year:num(x.year),type:text(x.type),doi:text(x.doi),url:text(x.url)});}); return {source_url:r.url,count:publications.length,publications}; }
  if(TOOL==="kraken_market_scraper") { const pair=String(input.pair||"XBTUSD").toUpperCase(); const source=`https://api.kraken.com/0/public/Ticker?pair=${encodeURIComponent(pair)}`; const r=await get(bf,source); const body=record(json(r.body)); if(array(body.error).length) throw new Error(array(body.error).join(", ")); const markets=Object.entries(record(body.result)).map(([resolved,v])=>{const x=record(v);return {pair:resolved,ask:num(array(x.a)[0]),bid:num(array(x.b)[0]),last:num(array(x.c)[0]),volume_today:num(array(x.v)[0]),volume_24h:num(array(x.v)[1]),vwap_today:num(array(x.p)[0]),vwap_24h:num(array(x.p)[1]),trades_today:num(array(x.t)[0]),trades_24h:num(array(x.t)[1]),low_today:num(array(x.l)[0]),low_24h:num(array(x.l)[1]),high_today:num(array(x.h)[0]),high_24h:num(array(x.h)[1]),open:num(x.o)};}); return {source_url:r.url,count:markets.length,markets}; }
  if(TOOL==="shopify_store_scraper") { const base=new URL(String(input.store_url)); const source=new URL(`/products.json?limit=${Math.min(limit,100)}`,base).toString(); const r=await get(bf,source,"http"); const products=array(record(json(r.body)).products).map(x=>record(x)).map(x=>{const variants=array(x.variants).map(record); const prices=variants.map(v=>num(v.price)).filter(v=>v>0); return compact({id:text(x.id),title:text(x.title),handle:text(x.handle),url:new URL(`/products/${text(x.handle)}`,base).toString(),vendor:text(x.vendor),product_type:text(x.product_type),published_at:text(x.published_at),price_min:prices.length?Math.min(...prices):undefined,price_max:prices.length?Math.max(...prices):undefined,currency:text(record(x.price_range).currency_code),available:variants.some(v=>Boolean(v.available)),variants:variants.length,image:text(record(x.image).src),tags:text(x.tags)});}); return {source_url:r.url,count:products.length,products}; }
  if(TOOL==="wordpress_posts_scraper") { const raw=String(input.site_url); const base=new URL(raw.endsWith("/")?raw:raw+"/"); const p=new URLSearchParams({per_page:String(Math.min(limit,50)),_fields:"id,date,modified,slug,status,link,title,excerpt,content,author"}); if(input.search)p.set("search",String(input.search)); const source=new URL(`wp-json/wp/v2/posts?${p}`,base).toString(); const r=await get(bf,source); const posts=array(json(r.body)).map(x=>record(x)).map(x=>compact({id:num(x.id),title:text(record(x.title).rendered),url:text(x.link),slug:text(x.slug),status:text(x.status),published_at:text(x.date),modified_at:text(x.modified),author_id:num(x.author),excerpt:text(record(x.excerpt).rendered),content_text:text(record(x.content).rendered).slice(0,3000)})); return {source_url:r.url,count:posts.length,posts}; }
  throw new Error("unknown tool");
});
